version: '3.8'

services:
    frontend:
        build:
            context: ./client
        ports:
            - '3000:3000'
        volumes:
            - ./client:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm run dev
        depends_on:
            - backend

    backend:
        build:
            context: ./server
        ports:
            - '5000:5000'
        volumes:
            - ./server:/app
            - /app/node_modules
        environment:
            - ./server/.env
        command: npm run dev
volumes:
    node_modules:
